# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - prefer_final_locals
    - avoid_relative_lib_imports
    - always_use_package_imports

analyzer:
#   exclude:
#     - path/to/excluded/files/**